apiVersion: v1
kind: deployable-architecture
metadata:
  description: "Paste your vibe, exhale, and ship \u2014 a static site on IBM Cloud\
    \ Object Storage (website enabled)."
  displayName: Vibe Code Landing Zone
  name: vibe-code-landing-zone
  version: 1.0.1
spec:
  deliveryMethod: terraform
  entrypoint: main.tf
  runtime:
    name: terraform
    version: '1.5'
  tags:
  - ibm-cloud
  - object-storage
  - static-website
  - website-ready
  - deployable-architecture
  - vibe-coding
  variables: variables.tf
