apiVersion: v1
kind: Solution
metadata:
  name: vibe-da-ibm-cloud-cos-static-website
  displayName: Vibe DA - IBM Cloud Static Website
  version: 1.0.3
  tags:
    - deployable-architecture
    - ibm-cloud
    - terraform
spec:
  source:
    url: https://github.com/goanalog/vibe-da-ibm-cloud
  artifacts:
    - name: main.tf
      type: terraform
    - name: variables.tf
      type: terraform
    - name: outputs.tf
      type: terraform
    - name: catalog.json
      type: metadata
  ui:
    icon: https://raw.githubusercontent.com/goanalog/vibe-da-ibm-cloud/main/assets/icon.png
    banner: https://raw.githubusercontent.com/goanalog/vibe-da-ibm-cloud/main/assets/banner.png
