apiVersion: v1
kind: deployable-architecture
metadata:
  name: vibe-da-ibm-cloud
  version: 1.0.6
  displayName: "Vibe DA — IBM Cloud Object Storage"
  description: "Instantly host any HTML or vibe-coded single-page app on IBM Cloud Object Storage."
spec:
  type: terraform
  terraformVersion: 1.12
  provider: IBM-Cloud/ibm
  license: Apache-2.0
  repository: https://github.com/goanalog/vibe-da-ibm-cloud
  readme: README.md
